Map strings={
  "hi":<String>["Hi,","Salut,"],
  "im":<String>["I'm ","Je m'apelle "],
  "name":<String>["Manuel Guilbert","Manuel Guilbert"],
  "face":<String>["This is my face","Ça, c'est moi"],
  "ouch":<String>["Ouch ! Why did you do that ?","Aïe ! Mais pourquoi ?"],
  "captcha":<String>["*In case your name is Captcha\nso you know I'm not a robot.","Et non, Captcha,\nje ne suis pas un robot!"],
  "thisIsMyLaptop":<String>["This is my laptop","Ça, c'est mon ordi"],
  "thisIsMyCamera":<String>["This is my camera","Ça, c'est mon appareil photo"],
  "teacher":<String>["I used to be a teacher but my love for IT is calling me back to app developement.","J'étais professeur des écoles mais ma passion pour l'informatique m'a rappellé au développement d'applications."],
  "more":<String>["Want to know more about me ?", "Vous voulez en savoir plus ?"],
  "thisWay":<String>["This way","Par ici"],
  "find":<String>['Find my work on Google Playstore',"Trouvez moi sur Google Playstore"],
  "description":<String>["I am a creative and dynamic developer.\nI love working on mobile applications,\nproviding nice UI/UX and features.","un développeur créatif et dynamique. \nJe suis passionné par le développement d'applications,\net la création d'UI/UX et de fonctionnalités ergonomiques."],
  "openSource":<String>["Open source projects are awesome\nand I sometimes contribute to them.","J'adore les projets Open Source\net j'y contribue parfois."],
  "techs":<String>["My loved technologies and tools are :","Mes outils et technos préférés sont :"],
  "travel":<String>["I had the chance to travel in some places and praticed languages a lot :\n","J'ai eu la chance de beaucoup voyager\n et de pratiquer les langues étrangères :\n"],
  "frenchEnglish":<String>["French : native           English : fluent","Francais : natif           Anglais : courant"],
  "spanish":<String>["Spanish: B2","Espagnol: B2"],
  "talk":<String>["Lets talk :","Contactez moi :",]
};